### ISSUE TITLE
Name with blank doesn't work

### ISSUE THREAD

**Issue by fakih** [HadrienMP/mob-time#2]
When I choose a name of the mob that contains a blank, it doesn't work

**Comment by HadrienMP** [comment]
Could you give an example ? I tried this and it seems to work : https://mob-time-server.herokuapp.com/with%20space

**Comment by HadrienMP** [comment]
For now I slugified the mob names, which means spaces will be replaced by dashes. It seemed better than enforcing a difficult rule on the client side for mob names. Right now the room url name and the room name are the same. The goal in the future will be to dissociate them. 

Is that fix ok for you ?

**Comment by fakih** [comment]
Everything is ok and working now. Thanks :)
